### ISSUE TITLE
Tailwind CSS - still part of this starter kit? why not?

### ISSUE THREAD

**Issue by redbar0n** [lpbayliss/nextjs-starter#15]
Tailwind is still referenced in the package.json description:

https://github.com/lpbayliss/lpbayliss-nextjs-starter/blob/6d4a54bdd7ef358ffd30efb7cc782c3dfe06125a/package.json#L4

But it doesn't seem to be a part of the project any more.

Could you give a few words as to why? I presume it was because of using Chakra UI instead, but then again I don't think they are competing?

**Comment by lpbayliss** [comment]
Sorry you're correct I should update that posthaste.

I moved away from Tailwind and this NextJS starter is basically a reflection of my current "get up and running fast" requirements.

The reasoning behind why is as you expected; the use of Chakra UI instead. I was using Tailwind as a means to speed up the development of my Styled Components and it slowly become more cumbersome than useful. Chakra UI provided some great theming and sensible default that have filled the same need Tailwind did more seemlessly.

**Comment by redbar0n** [comment]
Awesome, thanks.

Btw, for speed and future-proofing, you might want to check out React Testing Library as an alternative to Enzyme: https://testing-library.com/docs/react-testing-library/migrate-from-enzyme/

**Comment by lpbayliss** [comment]
I have recently converted to React Testing Library and loving it.
This project is clearly not a great reflection of my current taste aha!
